services:
  apartment-db:
    image: postgres:17-alpine
    container_name: apartment-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: apartments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d apartments"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db-network

  apartment-app:
    build: .
    container_name: apartment-app
    depends_on:
      apartment-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://apartment-db:5432/apartments
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2005
    networks:
      - db-network

networks:
  db-network:
    driver: bridge